service: serverless-localstack-poc

plugins:
  - serverless-localstack

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'local'}
  region: eu-west-1
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: serverless-localstack-poc

functions:
  hello:
    handler: handler.hello

custom:
  localstack:
    stages:
      - local
      - host: http://localhost
      - edgePort: 4566